### ISSUE TITLE
Build Failure. Is there a more stable way to download dependencies?

### ISSUE THREAD

**Issue by Hakazaba** [Inochi2D/i2d-imgui#29]
I'm receiving a lot of confusing errors when trying to build. I think some are related to downloads that don't complete but i'm unsure if there are other problems. Can i please have some guidence?

Log:
[Log.txt](https://github.com/user-attachments/files/18076290/Log.txt)

**Comment by playmer** [comment]
Fundamentally the issue here is you didn't clone the repo recursively, so you don't have the submodules. The CMake tried to clone them down but failed.

```batch
git clone --recurse-submodules -j8 https://github.com/Inochi2D/i2d-imgui.git
cd i2d-imgui
BuildDependencies_Windows.bat
```

Should get the dependencies set up correctly with a ton of permutations, you can just crack open the batch file to see what precisely it's building, but like I said, it's just a bunch of permutations of builds, likely you only need 1.

**Comment by Hakazaba** [comment]
Yeah that and a few other problems. Luna helped me fix it up.
